name: studio-nuxt-build
run-name: studio nuxt build

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package manager
        id: pkgman
        run: |
          if [ -f pnpm-lock.yaml ]; then
            echo "pm=pnpm" >> $GITHUB_OUTPUT
          elif [ -f yarn.lock ]; then
            echo "pm=yarn" >> $GITHUB_OUTPUT
          else
            echo "pm=npm" >> $GITHUB_OUTPUT
          fi

      - uses: pnpm/action-setup@v4
        if: ${{ steps.pkgman.outputs.pm == 'pnpm' }}
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          if [ "${{ steps.pkgman.outputs.pm }}" = "pnpm" ]; then pnpm install;
          elif [ "${{ steps.pkgman.outputs.pm }}" = "yarn" ]; then yarn install;
          else npm install; fi

      - name: Pre-render site
        run: |
          if [ "${{ steps.pkgman.outputs.pm }}" = "pnpm" ]; then pnpm exec nuxt generate;
          elif [ "${{ steps.pkgman.outputs.pm }}" = "yarn" ]; then yarn nuxt generate;
          else npx nuxt generate; fi
        env:
          NUXT_CONTENT_PREVIEW_API: https://api.nuxt.studio
          NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}

      - name: Add CNAME and .nojekyll
        run: |
          echo "www.poecommunity.help" > .output/public/CNAME
          touch .output/public/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./.output/public
